config/routes.rb
Fusuma::Application.routes.draw do
  root :to => 'welcome#index'

  devise_for :users

  get "trial", :to => 'projects#trial', :as => "trial_project"
  post "preview", :to => 'projects#preview', :as => "preview_trial_project"

  resources :users, :only => :show  do
    resources :projects do
      post "preview", :to => 'projects#preview', :on => :collection
      get "source", :to => 'projects#source', :on => :member
    end
  end

end

app/models/project.rb
# -*- coding: utf-8 -*-
class Project

  include Mongoid::Document
  include Mongoid::Timestamps

  field :name,   :type => String
  field :slide,  :type => String,  :default => <<EOS
<section id="home" class="step">
  <h1>Hello!</h1>
  <p>This is sample.</p>
</section>
<section class="step" data-x="1000">
   <h1>You can use the following HTML tags.</h1>
   <p>
    <code>&lt;section&gt;</code>
    <code> &lt;h1&gt;</code>
    <code> &lt;h2&gt;</code>
    <code> &lt;h3&gt;</code>
    <code> &lt;p&gt;</code>
    <code> &lt;img&gt;</code>
    <code> &lt;code&gt;</code>
    <code> &lt;b&gt;</code>
    <code> &lt;ul&gt;</code>
    <code> &lt;ol&gt;</code>
    <code> &lt;li&gt;</code>
    <code> &lt;i&gt;</code>
    <code> &lt;a&gt;</code>
    <code> &lt;br /&gt;</code>
  </p>
  <h2>You can use Twitter Bootstrap BaseCSS</h2>
  <h3>Typography</h3>
  <h1>h1. Heading 1</h1>
  <h2>h2. Heading 2</h2>
  <h3>h3. Heading 3</h3>
  <h3>Buttons</h3>
  <a class="btn">Button</a>
  <a class="btn btn-primary">Button</a>
  <a class="btn btn-info">Button</a>
  <a class="btn btn-success">Button</a>
  <a class="btn btn-warning">Button</a>
  <a class="btn btn-danger">Button</a>
  <a class="btn btn-inverse">Button</a>
  <h3>And more...</h3>
</section>

<section class="step" data-x="2000">
  <h1>Thanks to these products.</h1>
  <h2>Ruby on Rails</h2>
  <h2>Jmpress.js</h2>
  <h2>Twitter Bootstrap</h2>
  <h2>and so on!</h2>
  
</section>
<section class="step" data-x="3000">
  <p>いや、がんばって英語で書いたけど厳しいなコレ。</p>
  <p><a href="http://www.kosen-venture.com/">高専ベンチャープロジェクト</a>で作っていたものを作り直しました。</p>
  <p>本当だったら、<a href="http://twitter.com/neo6120">じぐそうさん</a>のJavascriptでもっとリッチなエディタになるはずだったんだけど、ボクの力不足で組み込めませんでした。</p>
  <p>ごめんないさい。</p>
  <p>てか、こんな手抜きな感じでごめんないさい。</p>
  <p><a href="http://twitter.com/Whimsical_Cat">変態猫先輩</a>のアートワークとかも組み込めませんでした。</p>
  <p>ごめんないさい。</p>
  <p>本当にごめんないさい。</p>
  <p>でも、あの合宿を経験できとてもよかったです。</p>
  <p>とってもよいチームで多くの時間を過ごすことができてよかったです。</p>
  <p>ナニワトモアレ、許してください。</p>
　<p> 2013年4月 <a href="http://twitter.com/toihrk">とい</a></p>
</section>
EOS

  field :public, :type => Boolean, :default => true

  belongs_to :user

  validates_presence_of :name
  validates_presence_of :slide

  before_save :sanitize_slide
  before_create :sanitize_slide

  after_create :attachment_user

  def sanitize_slide_for_preview
    sanitize_slide
  end

  private
  def sanitize_slide
    self.slide = Sanitize.clean(self.slide, 
                                :elements => ['section', 'h1', 'h2', 'h3', 'p', 'img', 
                                              'code', 'br', 'b', 'ul', 'ol','li', 'i', 'a'],
                                :attributes => {'section' => ['class', 'id', 'data-x'],
                                  'h1' => ['class'],
                                  'h2' => ['class'],
                                  'h3' => ['class'],
                                  'p'  => ['class'],
                                  'img' => ['src', 'alt', 'height', 'width', 'class'],
                                  'code' => ['class'],
                                  'b' => ['class'],
                                  'ul' => ['class'],
                                  'ol' => ['class'],
                                  'li' => ['class'],
                                  'i' => ['class'],
                                  'a' => ['href', 'title', 'target', 'class']})
  end

  def attachment_user
    self.user.projects << self
    self.user.save
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable

  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  field :name, :type => String
  field :bio,  :type => String

  validates_presence_of :name
  has_many :projects, :dependent => :delete
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => %w(show trial preview)
  layout 'slideshow', :only => %w(show preview)

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new(:user => current_user)
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
  end

  def trial
    @project = Project.new
  end

  def preview
    @project = Project.new
    @project.slide = params[:slide]
    @project.sanitize_slide_for_preview
    render :html => @project.slide, :action => :show
  end

  def source
    @project = Project.find(params[:id])
  end
    
  def create
    @project = Project.new(params[:project])
    @project.user = current_user
    if @project.save
      redirect_to user_project_path(:user_id => current_user, :id => @project.id)
    else
      render :action => :new
    end
  end

  def update
    @project = Project.find(params[:id])
    @project.attributes = params[:project]
    if @project.save
      redirect_to user_project_path(:user_id => current_user, :id => @project.id)
    else
      render :action => :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.delete
      redirect_to user_projects_path(current_user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    p @user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @projects= Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/.#application.html.haml
hiroki@HiokiBook-Pro.12107

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Fusuma"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Fusuma
          .container.nav-collapse
            %ul.nav.pull-right
              - if current_user.blank?
                %li
                  %a{:href => new_user_session_path} Sign in
                %li
                  %a{:href => new_user_registration_path} Sign up
              - else
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", "data-target" => "#", :href => "#"}
                    = current_user.name
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      %a{:href => user_projects_path(current_user.id)} Projects  
                    %li
                      %a{:href => edit_user_registration_path} Account
                    %li
                      = link_to "Sign out", destroy_user_session_path, :method => :delete
    .container-fluid

      .row-fluid
        = bootstrap_flash
        = yield
    
      %footer
        %p &copy; Kosen Venture 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/download.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Fusuma"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    / Please include Twitter bootstrap
    / BAD EXAMPLE
    / <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    / <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
    %style
      :css
        section.step {
          width: 900px;
          height: 400px;
          font-size: 1em;
          min-height: 500px;
          padding: 20px;
          background-color: white;
          display: block;
          border: 1px solid rgba(0, 0, 0, 0.15);
          -webkit-box-shadow: rgba(0, 0, 0, 0.05) -1px 1px 0, white -1px -1px 0 inset;
          -moz-box-shadow: rgba(0, 0, 0, 0.05) -1px 1px 0, white -1px -1px 0 inset;
          box-shadow: rgba(0, 0, 0, 0.05) -1px 1px 0, white -1px -1px 0 inset;
          -webkit-border-radius: 20px;
          -moz-border-radius: 20px;
          -ms-border-radius: 20px;
          -o-border-radius: 20px;
          border-radius: 20px;
        }


  %body
    .container-fluid
      .row-fluid
        #jmpress
          =  @project.slide
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    / Please include jquery, jmpress
    / <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    / BAD EXAMPLE
    / <script type="text/javascript" src="http://jmpressjs.github.com/jmpress.js/dist/jmpress.all.min.js"></script>
    :coffeescript
      $ ->
        $("#jmpress").jmpress()

app/views/layouts/slideshow.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Fusuma"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    /= stylesheet_link_tag "slideshow", :media => "all"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body.subtlepattern_gray_jean
    .navbar.navbar-fluid-top{"data-spy" => "affix"}
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Fusuma
          .container.nav-collapse
            %ul.nav.pull-right
              - if current_user.blank?
                %li
                  %a{:href => new_user_session_path} Sign in
                %li
                  %a{:href => new_user_registration_path} Sign up
              - else
                %li
                  %a{:href => user_projects_path(current_user.id)} Projects  
                %li
                  %a{:href => edit_user_registration_path}= current_user.name
                %li
                  = link_to "Sign out", destroy_user_session_path, :method => :delete
    .container-fluid

      .row-fluid
        #jmpress
          = yield

      %footer
        - if !current_user.blank?
          - if !@project.user.blank?
            - if current_user.id == @project.user.id
              %a.btn.btn-success{:href => edit_user_project_path(:user_id => current_user.id, :id => @project.id)} Edit
              = link_to "Delete", user_project_path(:user_id => current_user.id, :id => @project.id), :method => :delete, :class => "btn btn-danger"
            %a.btn{:href => source_user_project_path(:user_id => @project.user.id, :id => @project.id)} Source




    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    /= javascript_include_tag "slideshow"
    = javascript_include_tag "application"
    :coffeescript
      $ ->
        $("#jmpress").jmpress()

app/views/projects/.#edit.html.haml
hiroki@HiokiBook-Pro.12107

app/views/projects/.#index.html.haml
hiroki@HiokiBook-Pro.12107

app/views/projects/_form.html.haml
- if @project.errors.size > 0
  %h4 Error
  %p #{@project.errors.size} errors prohibited this product from being saved:
  %ul
    - @project.errors.full_messages.each do |msg|
      %li= msg


= form.label :name, "Name"
= form.text_field :name, :class => "input-xxlarge"

= form.label :slide, "Slide"
= form.text_area :slide, :class => "span12"
%span.help-block
  %p You can use the following HTML tags.
  %p
    %code &lt;section&gt;
    %code &lt;h1&gt;
    %code &lt;h2&gt;
    %code &lt;h3&gt;
    %code &lt;p&gt;
    %code &lt;img&gt;
    %code &lt;code&gt;
    %code &lt;b&gt;
    %code &lt;ul&gt;
    %code &lt;ol&gt;
    %code &lt;li&gt;
    %code &lt;i&gt;
    %code &lt;a&gt;
    %code &lt;br /&gt;

%label.checkbox
  = form.check_box :public
  Public?

app/views/projects/edit.html.haml
%h1 Edit #{@project.name}
%p Last Updated #{@project.updated_at}

= form_for(@project, :url => user_project_path(@project.id), :html => {:method => :put}) do |f|
  .form-ship
    = render  :partial => "form", :locals=>{:form=>f}
    .form-actions
      %a.btn.btn-success.btn-large#preview preview
      = f.submit "Update", :class => "btn btn-primary btn-large"

= form_tag(preview_user_projects_path(:user_id => current_user.id), :class => "preview_form", :target => :preview) do
  = hidden_field_tag "slide", "", :id => "slide"
  

app/views/projects/index.html.haml
%h1 Projects

%a.btn.btn-large.btn-primary{:href => new_user_project_path(current_user.id)} new

%ul.project-list
  - @projects.each do |project|
    %li
      %a{:href => user_project_path(:user_id => project.user.id, :id => project.id)}= project.name
      .pull-right
        %span.label.label-success Created at
        = project.created_at
        %span.label.label-info Updated at
        = project.updated_at
        %a.btn.btn-success{:href => edit_user_project_path(:user_id => current_user.id, :id => project.id)} Edit
        = link_to "Delete", user_project_path(:user_id => current_user.id, :id => project.id), :method => :delete, :class => "btn btn-danger"

app/views/projects/new.html.haml
%h1 New Project
%p Create as #{current_user.name}

= form_for(@project, :url => user_projects_path(current_user.id)) do |f|
  .form-ship
    = render  :partial => "form", :locals=>{:form=>f}
    .form-actions
      %a.btn.btn-success.btn-large#preview preview
      = f.submit "Create", :class => "btn btn-primary btn-large"

= form_tag(preview_user_projects_path(:user_id => current_user.id), :class => "preview_form", :target => :preview) do
  = hidden_field_tag "slide", "", :id => "slide"

app/views/projects/show.html.haml
-#%h1 Projects#show
-#%p Find me in app/views/projects/show.html.haml

-#= @project.name
-#= @project.slide

= raw @project.slide

-#= @project.public

-#%a{:href => edit_user_project_path(@project.id)} Edit
-#= link_to "Delete" user_project_path(@project.id), :mthod => :delete

app/views/projects/source.html.haml
%textarea#copyarea.span12{:disabled => ""}
  = render :file => 'layouts/download'
.pull-right
  %a.btn.btn-primary{:href => user_project_path(:user_id => @project.user.id, :id =>@project.id )} Show
  - if !current_user.blank?
    - if !@project.user.blank?
      - if current_user.id == @project.user.id
        %a.btn.btn-success{:href => edit_user_project_path(:user_id => current_user.id, :id => @project.id)} Edit
        = link_to "Delete", user_project_path(:user_id => current_user.id, :id => @project.id), :method => :delete, :class => "btn btn-danger"

app/views/projects/trial.html.haml
%h1 Trial

= form_tag(preview_trial_project_path, :class => "preview_form", :target => :preview) do
  = text_area_tag :slide, @project.slide, :class => "span12", :id => "copyarea"
  %span.help-block
    %p You can use the following HTML tags.
    %p
      %code &lt;section&gt;
      %code &lt;h1&gt;
      %code &lt;h2&gt;
      %code &lt;h3&gt;
      %code &lt;p&gt;
      %code &lt;img&gt;
      %code &lt;code&gt;
      %code &lt;b&gt;
      %code &lt;ul&gt;
      %code &lt;ol&gt;
      %code &lt;li&gt;
      %code &lt;i&gt;
      %code &lt;a&gt;
      %code &lt;br /&gt;

  = submit_tag "Preview", :class => "btn btn-primary btn-large"

app/views/users/show.html.haml
.hero-unit
  %h1= @user.name
  %p= @user.bio
%ul.project-list
  - @user.projects.each do |project|
    %li
      %a{:href => user_project_path(:user_id => project.user.id, :id => project.id)}= project.name
      .pull-right
        %span.label.label-success Created at
        = project.created_at
        %span.label.label-info Updated at
        = project.updated_at

app/views/welcome/index.html.haml
.hero-unit
  %h1 What was the Fusuma.
  %p.lead In the past, it was a Web service.
  %p.lead Service is still running with a chaotic source code.
  %p.lead This service is made from that failure.
  .pull-right
    - if current_user.blank?
      %a.btn.btn-large.btn-success{:href => trial_project_path} Trial
      %a.btn.btn-large.btn-primary{:href => new_user_session_path} Sign in
      %a.btn.btn-large.btn-primary{:href => new_user_registration_path} Sign up
    - else
      %a.btn.btn-large.btn-primary{:href => new_user_project_path(current_user.id)} Create

%h1 Recent Projects
%ul.project-list
  - @projects.each do |project|
    %li
      %a{:href => user_project_path(:user_id => project.user.id, :id => project.id)}= project.name
      .pull-right
        Created by
        %a.label{:href => user_path(project.user.id)}= project.user.name
        (#{project.created_at})